// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqYeAff8p0nX60uxzh9Xalr2FbIMOV8Uc',
    appId: '1:675252707090:web:9ac57dda3af11d1236ddcb',
    messagingSenderId: '675252707090',
    projectId: 'axios-finance',
    authDomain: 'axios-finance.firebaseapp.com',
    storageBucket: 'axios-finance.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjuUzVxzCJaOL9xCfUfAQbLBw18crBvY4',
    appId: '1:675252707090:android:8869bee3a3133e2836ddcb',
    messagingSenderId: '675252707090',
    projectId: 'axios-finance',
    storageBucket: 'axios-finance.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoNkqoivIzWXroode5CwB8ohlSXu9o-Ck',
    appId: '1:675252707090:ios:d57ff8467f37b69836ddcb',
    messagingSenderId: '675252707090',
    projectId: 'axios-finance',
    storageBucket: 'axios-finance.firebasestorage.app',
    iosBundleId: 'com.example.axios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoNkqoivIzWXroode5CwB8ohlSXu9o-Ck',
    appId: '1:675252707090:ios:d57ff8467f37b69836ddcb',
    messagingSenderId: '675252707090',
    projectId: 'axios-finance',
    storageBucket: 'axios-finance.firebasestorage.app',
    iosBundleId: 'com.example.axios',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqYeAff8p0nX60uxzh9Xalr2FbIMOV8Uc',
    appId: '1:675252707090:web:12424e4efb3492dd36ddcb',
    messagingSenderId: '675252707090',
    projectId: 'axios-finance',
    authDomain: 'axios-finance.firebaseapp.com',
    storageBucket: 'axios-finance.firebasestorage.app',
  );
}
